openapi: 3.0.3
info:
  title: Swagger TEST - OpenAPI 3.0
  description: |-
    This is test API SWAGGER
  termsOfService: http://swagger.io/terms/
  contact:
    email: Dimitra4@mail.ru
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.11
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: http://172.17.0.3:8000
tags:
  - name: test_requests
    description: All test request
    externalDocs:
      description: Please click)
      url: http://172.17.0.3:8000
paths:
  /get_names:
    get:
      tags:
        - test_requests
      summary: get information from endpoint
      description: test
      operationId: test
      requestBody:
        description: test
        required: false
      responses:
        '200':
          description: Successful operation
        '400':
          description: BAD request
        '404':
          description: Not Found
        '405':
          description: Validate by schema

  /hello:
    get:
      tags:
        - test_requests
      summary: get hello message
      description: test
      operationId: test
      requestBody:
        description: test
        required: false
      responses:
        '200':
          description: Successful operation
        '400':
          description: BAD request
        '404':
          description: Not Found
        '405':
          description: Validate by schema

  /get_info_by_user_id/{id:int}:
    get:
      tags:
        - test_requests
      summary: get user info
      description: test
      operationId: test
      requestBody:
        description: test
        content:
          application/json:
            schema:
                $ref: '#components/schema/json'
          application/xml:
            schema:
                $ref: '#components/schema/xml'
        required: true
      responses:
        '200':
          description: Successful operation
        '400':
          description: BAD request
        '404':
          description: Not Found
        '405':
          description: Validate by schema
  /get_user_balance_by_id/{id:int}:
    get:
      tags:
        - test_requests
      summary: get user balance
      description: test
      operationId: test
      requestBody:
        description: test
        content:
          application/json:
            schema:
                $ref: '#components/schema/json'
          application/xml:
            schema:
                $ref: '#components/schema/xml'
        required: true
      responses:
        '200':
          description: Successful operation
        '400':
          description: BAD request
        '404':
          description: Not Found
        '405':
          description: Validate by schema
  /get_name/{name}:
    get:
      tags:
        - test_requests
      summary: get user name
      description: test
      operationId: test
      requestBody:
        description: test
        content:
          application/json:
            schema:
                $ref: '#components/schema/json'
          application/xml:
            schema:
                $ref: '#components/schema/xml'
        required: true
      responses:
        '200':
          description: Successful operation
        '400':
          description: BAD request
        '404':
          description: Not Found
        '405':
          description: Validate by schema
  /get_total_balance:
    get:
      tags:
        - test_requests
      summary: get sum balance
      description: test
      operationId: test
      requestBody:
        description: test
        content:
          application/json:
            schema:
                $ref: '#components/schema/json'
          application/xml:
            schema:
                $ref: '#components/schema/xml'
        required: true
      responses:
        '200':
          description: Successful operation
        '400':
          description: BAD request
        '404':
          description: Not Found
        '405':
          description: Validate by schema

  /gets:
    get:
      tags:
        - test_requests
      summary: get
      description: test
      operationId: test
      requestBody:
        description: test
        content:
          application/json:
            schema:
                $ref: '#components/schema/json'
          application/xml:
            schema:
                $ref: '#components/schema/xml'
        required: true
      responses:
        '200':
          description: Successful operation
        '400':
          description: BAD request
        '404':
          description: Not Found
        '405':
          description: Validate by schema


  /deluser/{user_id}:
    delete:
      tags:
        - test_requests
      summary: delete user
      description: test
      operationId: test
      requestBody:
        description: test
        content:
          application/json:
            schema:
                $ref: '#components/schema/json'
          application/xml:
            schema:
                $ref: '#components/schema/xml'
        required: true
      responses:
        '200':
          description: Successful operation
        '400':
          description: BAD request
        '404':
          description: Not Found
        '405':
          description: Validate by schema